-- ============================================================
-- FPYC Hoops -- replace demo data with real Summer 3v3 Cup roster + schedule
-- Run in the Supabase SQL Editor. Safe to re-run (replaces all rows).
-- ============================================================

delete from public.players;
delete from public.games;
delete from public.practices;
delete from public.official_assignments;

insert into public.players (id, number, name, grade, school, guardian, phone, position, status, waiver, program, division, team) values
('p1', null, 'Ishaaq Adam', '2nd & 3rd', '', 'adamfamily0312@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p2', null, 'Ismaeel Adam', '4th & 5th', '', 'adamfamily0312@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p3', null, 'Jenny Ahn', '4th & 5th', '', 'hello323235@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p4', null, 'Hamza Ali', '4th & 5th', '', 'syednabilali@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p5', null, 'Neal Beesam', '4th & 5th', '', 'ashley@beesam.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p6', null, 'Michael Blessing', '2nd & 3rd', '', 'stephanie.wyckoff@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p7', null, 'Derrick Booker jr', '6th-8th', '', 'devita_shorter@msn.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p8', null, 'Alexander Chang', '6th-8th', '', 'dcnycjjpkr@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p9', null, 'Misdy Contreras Martínez', '2nd & 3rd', '', 'karrrymartines@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p10', null, 'Abby Cook', '6th-8th', '', 'dhciii@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p11', null, 'Alexsandra Cossio', '6th-8th', '', 'alexsandrocossio@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p12', null, 'kirubel daniel', '6th-8th', '', 'dagnu44@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p13', null, 'Anthony Del Fiore', '4th & 5th', '', 'jimdelf@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p14', null, 'Cole Denton', '6th-8th', '', 'erinldenton@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p15', null, 'Mason Drummey', '4th & 5th', '', 'saraabawi@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p16', null, 'Holden Duble', '6th-8th', '', 'martin.duble@verizon.net', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p17', null, 'Gio Flores', '6th-8th', '', 'jonrobflo@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p18', null, 'Nate Fuge', '4th & 5th', '', 'davidfuge@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p19', null, 'Joshua Garvin', '2nd & 3rd', '', 'tarhealrn08@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p20', null, 'Faris Hamid', '2nd & 3rd', '', 'hamid.ahmedm@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p21', null, 'Alex Handy', '6th-8th', '', 'wangl01@hotmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p22', null, 'Mira Hardwick', '6th-8th', '', 'sw0000sh11@hotmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p23', null, 'Emerson Harvey', '6th-8th', '', 'jeniharvey9@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p24', null, 'Ryan Harvey', '4th & 5th', '', 'jeniharvey9@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p25', null, 'Campbell Hastings', '2nd & 3rd', '', 'biohokie08@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p26', null, 'Declan Holmes', '6th-8th', '', 'slimkim35@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p27', null, 'Nathan Jones', '6th-8th', '', 'branjithan@yahoo.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p28', null, 'Norah Kamra- Rajpal', '2nd & 3rd', '', 'h.analyst777@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p29', null, 'Ethan Kim', '2nd & 3rd', '', 'bambina833@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p30', null, 'Arjun Kintgen', '6th-8th', '', 'ekintgen@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p31', null, 'Kabir Kintgen', '4th & 5th', '', 'ekintgen@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p32', null, 'Mishel Kletska', '6th-8th', '', 'rudolfina0908@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p33', null, 'BRUCE LEE', '6th-8th', '', 'blee5451@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p34', null, 'Kenson Lee', '6th-8th', '', 'maziejae@aol.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p35', null, 'Abu Bakr Lodin', '4th & 5th', '', 'shukriahd@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p36', null, 'Rhys Mancil', '6th-8th', '', 'mancl.amy@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p37', null, 'Avery McCray', '4th & 5th', '', 'rj.mccray@irs.gov', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p38', null, 'Levi McCray', '2nd & 3rd', '', 'rj.mccray@irs.gov', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p39', null, 'Aditya Menon', '6th-8th', '', 'binds29@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p40', null, 'Isaac Nunes', '4th & 5th', '', 'nunes8787@hotmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p41', null, 'Aiden Oh', '2nd & 3rd', '', 'mike_oh1981@hotmail.co.kr', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p42', null, 'Owen Pham', '6th-8th', '', 'phamharvey@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p43', null, 'Oscar Potter', '2nd & 3rd', '', 'liciaroberts@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p44', null, 'Quentin potter', '6th-8th', '', 'liciaroberts@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p45', null, 'Adrian Prado', '6th-8th', '', 'twojagerbombs@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p46', null, 'Benjamin Quinn', '4th & 5th', '', 'james.john.quinn@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p47', null, 'Alonso Rivera', '6th-8th', '', 'twojagerbombs@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p48', null, 'Antonio Rivera', '2nd & 3rd', '', 'twojagerbombs@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p49', null, 'Lucas Saal', '4th & 5th', '', 'b_saal@yahoo.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p50', null, 'Lucas RR Seal', '2nd & 3rd', '', 'seals_home@yahoo.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p51', null, 'Thomas RR Seal', '2nd & 3rd', '', 'seals_home@yahoo.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p52', null, 'Drea Seaton', '6th-8th', '', 'deenarusso@mac.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p53', null, 'Rylen Shajib', '2nd & 3rd', '', 'milani.shajib@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p54', null, 'Jaxson Shajib', '2nd & 3rd', '', 'milani.shajib@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 2nd-3rd Boys', 'Rising 2nd-3rd Boys'),
('p55', null, 'Hannah Swiercz', '2nd & 3rd', '', 'kelly.cage@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p56', null, 'Philip Tran', '4th & 5th', '', 'marwei.tam@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 4th-5th Boys', 'Rising 4th-5th Boys'),
('p57', null, 'Chase Vadakedathu', '6th-8th', '', 'linandcass@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Rising 6th-8th Boys', 'Rising 6th-8th Boys'),
('p58', null, 'Sarah Vadakedathu', '6th-8th', '', 'linandcass@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)'),
('p59', null, 'Kyrie Varela', '4th & 5th', '', 'zelda.varela@gmail.com', '', '', 'active', true, '3v3 Summer Cup', 'Girls 3v3 (2nd-8th)', 'Girls 3v3 (2nd-8th)');

insert into public.games (id, team, opponent, day, date, month, weekday, "time", location, home, status, score_pin) values
('g231', 'Rising 2nd-3rd Boys', 'Week 1: Opening Night Tournament', 'Tue, Jun 16', 16, 'Jun', 'Tue', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '2824'),
('g232', 'Rising 2nd-3rd Boys', 'Week 2: King of the Court', 'Tue, Jun 23', 23, 'Jun', 'Tue', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '1409'),
('g233', 'Rising 2nd-3rd Boys', 'Week 3: World Cup Night', 'Tue, Jun 30', 30, 'Jun', 'Tue', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '5506'),
('g234', 'Rising 2nd-3rd Boys', 'Week 4: Rivalry Night', 'Tue, Jul 7', 7, 'Jul', 'Tue', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '5012'),
('g235', 'Rising 2nd-3rd Boys', 'Week 5: All-Star Challenge', 'Tue, Jul 14', 14, 'Jul', 'Tue', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '4657'),
('g236', 'Rising 2nd-3rd Boys', 'Week 6: Summer Cup Finals', 'Tue, Jul 21', 21, 'Jul', 'Tue', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '3286'),
('gg1', 'Girls 3v3 (2nd-8th)', 'Week 1: Opening Night Tournament', 'Tue, Jun 16', 16, 'Jun', 'Tue', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '2679'),
('gg2', 'Girls 3v3 (2nd-8th)', 'Week 2: King of the Court', 'Tue, Jun 23', 23, 'Jun', 'Tue', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '9935'),
('gg3', 'Girls 3v3 (2nd-8th)', 'Week 3: World Cup Night', 'Tue, Jun 30', 30, 'Jun', 'Tue', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '2424'),
('gg4', 'Girls 3v3 (2nd-8th)', 'Week 4: Rivalry Night', 'Tue, Jul 7', 7, 'Jul', 'Tue', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '7912'),
('gg5', 'Girls 3v3 (2nd-8th)', 'Week 5: All-Star Challenge', 'Tue, Jul 14', 14, 'Jul', 'Tue', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '1520'),
('gg6', 'Girls 3v3 (2nd-8th)', 'Week 6: Summer Cup Finals', 'Tue, Jul 21', 21, 'Jul', 'Tue', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '1488'),
('g451', 'Rising 4th-5th Boys', 'Week 1: Opening Night Tournament', 'Thu, Jun 18', 18, 'Jun', 'Thu', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '2535'),
('g452', 'Rising 4th-5th Boys', 'Week 2: King of the Court', 'Thu, Jun 25', 25, 'Jun', 'Thu', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '4582'),
('g453', 'Rising 4th-5th Boys', 'Week 3: World Cup Night', 'Thu, Jul 2', 2, 'Jul', 'Thu', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '4811'),
('g454', 'Rising 4th-5th Boys', 'Week 4: Rivalry Night', 'Thu, Jul 9', 9, 'Jul', 'Thu', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '9279'),
('g455', 'Rising 4th-5th Boys', 'Week 5: All-Star Challenge', 'Thu, Jul 16', 16, 'Jul', 'Thu', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '1434'),
('g456', 'Rising 4th-5th Boys', 'Week 6: Summer Cup Finals', 'Thu, Jul 23', 23, 'Jul', 'Thu', '6:30 PM - 7:30 PM', 'TBD', true, 'scheduled', '4257'),
('g681', 'Rising 6th-8th Boys', 'Week 1: Opening Night Tournament', 'Thu, Jun 18', 18, 'Jun', 'Thu', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '9928'),
('g682', 'Rising 6th-8th Boys', 'Week 2: King of the Court', 'Thu, Jun 25', 25, 'Jun', 'Thu', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '7873'),
('g683', 'Rising 6th-8th Boys', 'Week 3: World Cup Night', 'Thu, Jul 2', 2, 'Jul', 'Thu', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '4611'),
('g684', 'Rising 6th-8th Boys', 'Week 4: Rivalry Night', 'Thu, Jul 9', 9, 'Jul', 'Thu', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '8359'),
('g685', 'Rising 6th-8th Boys', 'Week 5: All-Star Challenge', 'Thu, Jul 16', 16, 'Jul', 'Thu', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '5557'),
('g686', 'Rising 6th-8th Boys', 'Week 6: Summer Cup Finals', 'Thu, Jul 23', 23, 'Jul', 'Thu', '7:30 PM - 8:30 PM', 'TBD', true, 'scheduled', '1106');

insert into public.practices (id, team, date, "time", gym, type, rsvp, notes) values
('pdb1_1', 'Rising 2nd-3rd Boys', 'Mon, Jun 1', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb1_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jun 1', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb1_3', 'Rising 4th-5th Boys', 'Mon, Jun 1', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb1_4', 'Rising 6th-8th Boys', 'Mon, Jun 1', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pda1_1', 'Rising 2nd-3rd Boys', 'Mon, Jun 1', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda1_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jun 1', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda1_3', 'Rising 4th-5th Boys', 'Mon, Jun 1', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda1_4', 'Rising 6th-8th Boys', 'Mon, Jun 1', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pdb2_1', 'Rising 2nd-3rd Boys', 'Mon, Jun 15', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb2_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jun 15', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb2_3', 'Rising 4th-5th Boys', 'Mon, Jun 15', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb2_4', 'Rising 6th-8th Boys', 'Mon, Jun 15', '6:00-7:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Beginner group'),
('pda2_1', 'Rising 2nd-3rd Boys', 'Mon, Jun 15', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda2_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jun 15', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda2_3', 'Rising 4th-5th Boys', 'Mon, Jun 15', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda2_4', 'Rising 6th-8th Boys', 'Mon, Jun 15', '7:00-8:00 PM', 'Providence ES', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pdb3_1', 'Rising 2nd-3rd Boys', 'Mon, Jun 29', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb3_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jun 29', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb3_3', 'Rising 4th-5th Boys', 'Mon, Jun 29', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb3_4', 'Rising 6th-8th Boys', 'Mon, Jun 29', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pda3_1', 'Rising 2nd-3rd Boys', 'Mon, Jun 29', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda3_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jun 29', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda3_3', 'Rising 4th-5th Boys', 'Mon, Jun 29', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda3_4', 'Rising 6th-8th Boys', 'Mon, Jun 29', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pdb4_1', 'Rising 2nd-3rd Boys', 'Mon, Jul 13', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb4_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jul 13', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb4_3', 'Rising 4th-5th Boys', 'Mon, Jul 13', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb4_4', 'Rising 6th-8th Boys', 'Mon, Jul 13', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pda4_1', 'Rising 2nd-3rd Boys', 'Mon, Jul 13', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda4_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jul 13', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda4_3', 'Rising 4th-5th Boys', 'Mon, Jul 13', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda4_4', 'Rising 6th-8th Boys', 'Mon, Jul 13', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pdb5_1', 'Rising 2nd-3rd Boys', 'Mon, Jul 20', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb5_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jul 20', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb5_3', 'Rising 4th-5th Boys', 'Mon, Jul 20', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb5_4', 'Rising 6th-8th Boys', 'Mon, Jul 20', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pda5_1', 'Rising 2nd-3rd Boys', 'Mon, Jul 20', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda5_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jul 20', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda5_3', 'Rising 4th-5th Boys', 'Mon, Jul 20', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda5_4', 'Rising 6th-8th Boys', 'Mon, Jul 20', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pdb6_1', 'Rising 2nd-3rd Boys', 'Mon, Jul 27', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb6_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jul 27', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb6_3', 'Rising 4th-5th Boys', 'Mon, Jul 27', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pdb6_4', 'Rising 6th-8th Boys', 'Mon, Jul 27', '6:00-7:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Beginner group'),
('pda6_1', 'Rising 2nd-3rd Boys', 'Mon, Jul 27', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda6_2', 'Girls 3v3 (2nd-8th)', 'Mon, Jul 27', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda6_3', 'Rising 4th-5th Boys', 'Mon, Jul 27', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group'),
('pda6_4', 'Rising 6th-8th Boys', 'Mon, Jul 27', '7:00-8:00 PM', 'Fairfax HS', 'Player Development', 0, 'Player Development - Intermediate/Advanced group');

update public.players set program = 'Recreation' where program = '3v3 Summer Cup';
